version: '3.8'

services:
  jenkins_agent_1:
    image: jenkins/ssh-agent:jdk17
    privileged: true
    user: root
    container_name: jenkins_agent_1
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    networks:
      - my-network

networks:
  my-network:
    name: my-jenkins-network