version: '3.8'
services:
    jenkins-contoller:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: jenkins-controller
      volumes:
        - './jenkins_configuration:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'
      networks:
        - my-network
    agent-1:
      image: jenkins/ssh-agent:debian-jdk17
      privileged: true
      user: root
      container_name: agent-1
      expose:
        - 22
      environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7KX6YVEXfIoJYD7F8EOX3WO0mZ7JIjH5qkV70bAM1LKn+Jn/QjXuRS0elBLFERUUXkbmv8B9Tx0AO2RfW0TRcmbFj+IhePU7YjiGrvC+YSDUatERBJ08OFJNBdhHwqBsozz8TvljdXyXfv0WySXwMNobPDTjZo7KQf90cvNuJ8/WUX9+sx/8evb3nTkbrtyR4de6YqvDRD8xSN9jSakYmC6GU+Dvipy+V/8bU7kSLezBeAtsCnRvKKQ1in9bjjV4qyKkMCMT7c3JOXY5MuyTlv2XqpR5id822nfj1RuM+ZYxK/k7npAjCG3ME/smJ+fzXigDigZe2Cxv7HhwuETw/KSZRXFvu+5JqE0Gox7AFpHGjucuFYwkqJ1qi31uoZIGnCAlkWCuBrt/RXuMH5fpUhTAo2UYEDpT6rF+njkU/h5dV3cE43VmynkvI3hr1jw+yKlspCJwGbvkqX3PWKjUE5eMAi9TDPCrs+2+RgrF0Zv21dvkAz2Vfb89KAaUrOD0= revit@mxlinux
      networks:
        - my-network
networks:
  my-network:
    name: my-jenkins-network